persistentVolumeClaim:
  storage: 10Gi
  storageClassName: gp3

containers:
  group1-redis:
    image:
      repository: 343434343434.dkr.ecr.eu-west-1.amazonaws.com/comp/redis
      pullPolicy: IfNotPresent
      tag: production
      