# Default values for eck.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: elk
version: 8.2.0

##### Elasticseacrh config #####
elasticsearch:

  replica: 1

  elastiConfig:
    node.store.allow_mmap: false

  accessModes:
  - ReadWriteOnce

  metadata:
    name: elasticsearch-data

  resources:
    requests:
      storage: 256Gi

  storageClassName: gp3


##### Kibana config ######

kibana:
  replica: 1

  kibanaConfig:
    monitoring.kibana.collection.enabled: false

  podTemplate:
    metadata:
      labels:
        scrape: kb

  http:
    tls:
      selfSignedCertificate:
        disabled: true

  service:
    name: kibana-kb-http
    type: ClusterIP
    port: 5601

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "true"
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - paths:
          - path: /
        subdomain: kibana
        domain: f_item.com
        pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

###### Filebeat Config  ############

filebeat:
  config:
    filebeat.idle_timeout: 5s
    filebeat.spool_size: 2048
    logging.level: info

    fields:
      host: ${HOSTNAME:unknown}
      environment: ${ENVIRONMENT:unknown}

    filebeat.inputs:
      - type: log
        paths:
          - /LOGS/*/apache2/*access.log*
          - /LOGS/apache2/*access.log*
        fields_under_root: true
        fields:
          doctype: apache_access

      - type: log
        paths:
          - /LOGS/*/*/*laravel*
          - /LOGS/*/*laravel*
        fields_under_root: true
        fields:
          doctype: laravel
        multiline:
          pattern: '^\['
          match: after
          negate: true

      - type: log
        paths:
        - /LOGS/*/*/*lumen*
        - /LOGS/*/*lumen*
        fields_under_root: true
        fields:
          doctype: laravel
        multiline:
          pattern: '^\['
          match: after
          negate: true


      - type: log
        paths:
          - /LOGS/group1*/dfg/crpt*.log
          - /LOGS/group1*/dfg/thermal-work.log
          - /LOGS/group1*/dfg/sync*.log
          - /LOGS/group1*/dfg/rp_crpt.log
          - /LOGS/group1*/dfg/lmd_adv.log
          - /LOGS/group1*/dfg/lmd_adv_filter.log
          - /LOGS/group1*/dfg/platform.log
          - /LOGS/dfg/crpt*.log
          - /LOGS/dfg/thermal-work.log
          - /LOGS/dfg/sync*.log
          - /LOGS/dfg/rp_enc.log
          - /LOGS/dfg/adv.log
          - /LOGS/dfg/adv_filter.log
          - /LOGS/dfg/platform.log
        fields_under_root: true
        fields:
          doctype: group1_python_v1
        multiline:
          pattern: '^\['
          negate: true
          match: after


      - type: log
        paths:
          - /LOGS/group1*/dfg/param.log
          - /LOGS/group1*/dfg/g_app.log
          - /LOGS/group1*/dfg/growthCharts.log
          - /LOGS/group1*/dfg/thermal.log
          - /LOGS/group1*/dfg/proc.log
          - /LOGS/group1*/dfg/omim.log
          - /LOGS/group1*/dfg/collater.log
          - /LOGS/group1*/dfg/veri.log
          - /LOGS/group1*/dfg/quick_post.log
          - /LOGS/group1*/dfg/quick_points.log
          - /LOGS/dfg/param.log
          - /LOGS/dfg/g_app.log
          - /LOGS/dfg/growthCharts.log
          - /LOGS/dfg/thermal.log
          - /LOGS/dfg/proc.log
          - /LOGS/dfg/omim.log
          - /LOGS/dfg/collater.log
          - /LOGS/dfg/veri.log
          - /LOGS/dfg/quick_post.log
          - /LOGS/dfg/quick_points.log
        fields_under_root: true
        fields:
          doctype: group1_v1
        multiline:
          pattern: '^\['
          negate: true
          match: after


      - type: log
        paths:
          - /LOGS/group1/phbot/*.log
          - /LOGS/group1*/dfg/thCndn9HM.log
          - /LOGS/phbot/*.log
          - /LOGS/dfg/thCndn9HM.log
        fields_under_root: true
        fields:
          doctype: group1_not_structured

      - type: log
        paths:
          - /LOGS/install*/**/*.log*
        fields_under_root: true
        fields:
          doctype: installer

      - type: log
        paths:
          - /LOGS/python-services/*/*.log
        fields_under_root: true
        fields:
          doctype: python-services
        multiline:
          pattern: '^\['
          match: after
          negate: true

      - type: container
        paths:
          - /var/log/containers/*.log

      - type: log
        paths:
          - "/var/log/startupscript.log"
          - "/var/log/log/kubelet.log"
          - "/var/log/kube-proxy.log"
          - "/var/log/kube-apiserver.log"
          - "/var/log/kube-controller-manager.log"
          - "/var/log/kube-scheduler.log"
          - "/var/log/rescheduler.log"
          - "/var/log/glbc.log"
          - "/var/log/cluster-autoscaler.log"
        symlinks: true
        json.message_key: log
        json.keys_under_root: true
        json.add_error_key: true
        multiline.pattern: '^\s'
        multiline.match: after
        fields_under_root: true
        fields:
          doctype: kube-logs
        tail_files: false

      - type: log
        paths:
          - /LOGS/tls/*.log
        exclude_lines: ['^.*Receiving response.*' , '^.*Connection can be kept alive indefinitely.*' , '^.*Parsing response as.*', '^.*EofSensorInputStream.*']
        fields_under_root: true
        fields:
          doctype: tls
        multiline:
          pattern: '^\['
          negate: true
          match: after

      - type: log
        paths:
          - /LOGS/logstash/**.log
          - /LOGS/kibana/**.log
          - /LOGS/kibana-gateway/**.log
          - /LOGS/elastalert/**.log
          - /LOGS/curator/**.log
        fields_under_root: true
        fields:
          doctype: elk

    processors:
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
        matchers:
        - logs_path:
            logs_path: "/var/log/containers/"

    output.elasticsearch:
      host: ${NODE_NAME}
      hosts:
      - eck-elasticsearch-es-default:9200
      password: ${ELASTICSEARCH_PASSWORD}
      protocol: https
      ssl.verification_mode: none
      username: elastic

#####   OTHER Values ######

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80