{{- if .Values.SecretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.SecretStore.name | default (printf "%s-aws-secretsmanager" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.SecretStore.region | default "eu-west-1" }}
      {{- if .Values.SecretStore.roleArn }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.SecretStore.serviceAccountName | default "external-secrets-sa" }}
            namespace: {{ .Values.SecretStore.serviceAccountNamespace | default "eso-system" }}
      {{- end }}
{{- end }}