- hosts: "k8s"
  gather_facts: no
  become: true
  tasks:
    - name: Check if kube config is present
      stat:
        path: /home/jenkins/.kube/config
      register: config_present
    - name: Create .kube directory
      ansible.builtin.file:
        path: /home/jenkins/.kube
        state: directory
        owner: jenkins
        group: users
        mode: '0744'
        recurse: yes
      when: not config_present.stat.exists
    - name: Copy config file
      ansible.builtin.copy:
        src: /home/ubuntu/.kube/config
        dest: /home/jenkins/.kube/config
        remote_src : true
        owner: jenkins
        group: users
        mode: '0700'
      when: not config_present.stat.exists
- hosts: "k8s"
  pre_tasks :
    - include_vars: inventory/group_vars/k8s/helm.yml
    - name: Compress ECK charts
      shell: "cd ../comp-helm-charts; tar -cvf eck_helm_chart.tar eck"
      delegate_to: localhost
    - name: Create directory workspace
      shell: "mkdir -p workspace/comp-helm-charts &> /dev/null"
    - name: Create scale-operations directory
      shell: "mkdir -p scale-operations &> /dev/null"
    - name: Copy scale-down script
      ansible.builtin.copy:
        src: ../jenkins/scale-operations/scale-down.sh
        dest: /home/jenkins/scale-operations
        force: yes
    - name: Copy scale-up script
      ansible.builtin.copy:
        src: ../jenkins/scale-operations/scale-up.sh
        dest: /home/jenkins/scale-operations
        force: yes        
    - name: Copy ECK chart
      ansible.builtin.copy:
        src: ../comp-helm-charts/eck_helm_chart.tar
        dest: /home/jenkins/workspace
    - name: UnCompress ECK chart
      shell: "cd workspace; tar -xvf eck_helm_chart.tar -C comp-helm-charts"
    - name: Compress chart values
      shell: "cd ../helm-values; tar -cvf {{ env_var }}_helm_values.tar {{ env_var }}"
      delegate_to: localhost
    - name: Create dierectory workspace/helm-values
      shell: "mkdir -p workspace/helm-values &> /dev/null"
    - name: Copy chart values
      ansible.builtin.copy:
        src: ../helm-values/{{ env_var }}_helm_values.tar
        dest: "{{ helm_values_dir }}"
    - name: UnCompress chart values
      shell: "cd {{ helm_values_dir }}; tar -xvf {{ env_var }}_helm_values.tar"
  roles:
    - role: addon.externalDns
    - role: addon.nginx-ingress
    - role: addon.nginx-external
    - role: addon.elk
    - role: addon.clusterautoscaler
    - role: addon.kube-prometheus