- hosts: "k8s"
  become: true
  pre_tasks :
  - include_vars: inventory/group_vars/k8s/helm.yml
  - name: Copy scripts
    ansible.builtin.copy:
      src: "./scripts/{{ item }}.sh"
      dest: "/home/jenkins/{{ item }}.sh"
      mode: '0755'
      force: yes
    loop: "{{ script_list }}"
  tasks:
  - include_vars: inventory/group_vars/k8s/helm.yml
  - name: "Scripts as a service"
    ansible.builtin.template:
      src: "./scripts/template_service.j2"
      dest: "/etc/systemd/system/{{ item }}.service"
      force: yes
    with_items: "{{ script_list }}"
  - name: Reload systemd to pick up new service files
    systemd:
      daemon_reload: yes
  - name: Enable service
    systemd:
      name: "{{ item }}.service"
      enabled: yes
      state: started
    loop: "{{ script_list }}"