
deployment:
  enabled: false

nameOverride: ""
fullnameOverride: "group1-redis"

statefulset:
  replicas: 1

persistentVolumeClaim:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  accessModes:
    - ReadWriteOnce
  storage: 10Gi
  storageClassName: gp2

imagePullSecrets:
  - name: regsecret

containers:
  group1-redis:
    image:
      repository: 343434343434.dkr.ecr.eu-west-1.amazonaws.com/comp/redis
      pullPolicy: IfNotPresent
      tag: latest
    env: []
    securityContext: {}
    ports:
      - name: redis
        containerPort: 6379
        protocol: TCP
    resources:
      requests:
        cpu: 50m
        memory: 601Mi
    livenessProbe: {}
    readinessProbe: {}
    volumeMounts:
      - name: logs
        mountPath: /var/log
      - name: group1-redis-data-volume
        mountPath: /data

serviceAccount:
  create: false
  annotations: {}
  name: "default"

podAnnotations: {}

podSecurityContext: {}

service:
  enabled: true
  type: ClusterIP
  annotations: {}
  port: 6379
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379

ingress:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

volumes:
  - name: logs
    hostPath:
      path: /LOGS/group1-redis
      type: ""
  - name: group1-redis-data-volume
    persistentVolumeClaim:
      claimName: group1-redis-data
