deployment:
  enabled: true

replicaCount: 1

image:
  repository: 343434343434.dkr.ecr.eu-west-1.amazonaws.com/comp/group1
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: "group1-thermal-py3"

serviceAccount:
  create: false
  annotations: {}
  name: "default"

podSecurityContext: {}

securityContext: {}

ports: []

service:
  enabled: false

ingress:
  enabled: false

resources:
  requests:
    cpu: 500m
    memory: 1G

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "25%"
    maxUnavailable: "25%"

command: []
args: []
env:
  - name: ENV
    value: "prod"
  - name: WORKER
    value: "thermal-post_worker"
  - name: ITEM_VAL_ENDPOINT
    value: "http://item-app"
  - name: ENVIRONMENT
    valueFrom:
      configMapKeyRef:
        key: environment
        name: env-config

probes:
  liveness: {}
  readiness: {}

volumeMounts:
  - name: logs
    mountPath: /var/logs/supervisor/

volumes:
  - name: logs
    hostPath:
      path: /LOGS/group1-thermal-py3
      type: ""
