controller:
  containerPort:
    http: 80
    https: 80
    tohttps: 2443
  config:
    http-snippet: |
      server {
        listen 2443;
        return 308 https://\$host\$request_uri;
      }
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:101010101010:certificate/22222a2a-2a22-2222-2222-2a222a222222"
    loadBalancerSourceRanges:
      - 0.0.0.0/0
    enableHttp: true
    enableHttps: true
    ports:
      https: 443
      http: 80
    targetPorts:
      https: http
      http: tohttps
  ingressClassResource:
    name: nginx-external
    controllerValue: "k8s.io/nginx-external"

