
deployment:
  enabled: true

replicaCount: 1

image:
  repository: 343434343434.dkr.ecr.eu-west-1.amazonaws.com/comp/platform-api
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: regsecret

nameOverride: ""
fullnameOverride: "platform-api"

serviceAccount:
  create: false
  annotations: {}
  name: "default"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

ports:
  - name: http
    containerPort: 80
    protocol: TCP
  - name: metrics
    containerPort: 9000
    protocol: TCP

service:
  type: ClusterIP
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:939393939393:certificate/f0baf5bb-083f-4f1e-b6f1-ea8b38ec72b1
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  port: 80
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 80
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80

ingress:
  enabled: true
  servicePort: 80
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS, DELETE, PATCH
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.org/client-max-body-size: 5000m
  ingressClassName: "nginx-external"
  useGlobalDomain: "external"
  hosts:
    - subdomain: api
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    memory: 4G
  requests:
    cpu: 500m
    memory: 1400Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: ENVIRONMENT
    valueFrom:
      configMapKeyRef:
        key: environment
        name: env-config

probes:
  liveness:
    exec:
      command:
        - liveness-check
    failureThreshold: 3
    initialDelaySeconds: 3
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
  readiness:
    exec:
      command:
        - readiness-check
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 3
    successThreshold: 1
    timeoutSeconds: 3

volumeMounts:
  - name: logs
    mountPath: /var/log

volumes:
  - name: logs
    hostPath:
      path: /LOGS/platform-api
      type: ""
